###

GET http://localhost:3000/user/getAll

###

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "name" : "Yujjk Ljbhkljsbvjesbvljsrb",
    "email" : "ulk@northeastern.edu",
    "password": "werHtjshvhy@123"
}

###

PUT http://localhost:3000/user/edit?email=rs@northeastern.edu
Content-Type: application/json

{
    "name" : "Ruch jlkskejvn",
    "password": "Qwerty@123566"
}

###

DELETE http://localhost:3000/user/delete?email=rs@northeastern.edu

###

